from datetime import datetime

from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required

#Forms
from posts.forms import PostForm

#Models
from posts.models import Post

# from django.http import HttpResponse
# Create your views here.

# Generated by https://quicktype.io

# Generated by https://quicktype.io


@login_required
def list_posts(request):
  
  posts = Post.objects.all().order_by('-created') #para que sean del mas nuevo al mas viejo 
  return render(request, 'posts/feed.html', {'posts': posts})

@login_required
def create_post(request):
  """Create new Post view"""
  if  request.method == 'POST':
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect('posts:feed')
  else:
    form = PostForm()

  return render(
    request = request,
    template_name= 'posts/new.html',
    context={
      'form': form,
      'user': request.user,
      'profile': request.user.profile
    }
  )